### ISSUE TITLE
Avatar Fallback should be N/A

### ISSUE THREAD

**Issue by timjacksonm** [timjacksonm/Toss-Up#29]
Currently the Avatar uses the profiles image. If profile image is undefined it uses the profiles first & last name initials. If profile for some reason doesn't have initials we should setup "N/A" as the ultimate fallback.

- [ ] Update avatar.tsx adding ?? "N/A"

```
<Avatar.Fallback>
        {initials ?? "N/A"}
 </Avatar.Fallback>
```
Before
![image](https://user-images.githubusercontent.com/76879054/221425138-8ec3f5e7-39a8-45e7-89e2-fc9fefe33a92.png)

After change
![image](https://user-images.githubusercontent.com/76879054/221425126-10ab2d44-b03e-45f5-a31b-5cb402215b58.png)

**Comment by alindsharmasimply** [comment]
Hey @timjacksonm , I want to work on this. Can you please tell me how to get the ENV file?

**Comment by alindsharmasimply** [comment]
Hey @timjacksonm , any pointers on how to get can I get the .env file?

**Comment by timjacksonm** [comment]
@alindsharmasimply Hi, thanks for your interest. I haven't quite setup this project so its easy to make contributions yet. If you would like to take this ticket. I can assign it to you. I will get back to you as soon as I have the project setup ready for contributions.

**Comment by alindsharmasimply** [comment]
Sure @timjacksonm, please assign this one to me.
Also, please keep me in loop.
Thanks!

**Comment by timjacksonm** [comment]
@alindsharmasimply Hey! I just sent you an email @ alindsharmasimply@gmail.com with the information you need to get started on this contribution. Please message me here if you have any further questions.

**Comment by alindsharmasimply** [comment]
Thanks @timjacksonm 👍. Have raised a PR for this issue. Kindly check it out.

**Comment by timjacksonm** [comment]
> Thanks @timjacksonm +1. Have raised a PR for this issue. Kindly check it out.

Your branch that you submitted a PR under was out of sync with Main. If you are still wanting to complete this, I left a comment on your PR on what you will need to do.
